### ISSUE TITLE
exposed stack library module is not visible

### ISSUE THREAD

**Issue by yaitskov** [haskell-hint/hint#125]
Hi,

I am trying to import library module inside evaluated script file.
hint doesn't see such module.
I though that `library: ` section with `exposed-modules:` is equivalent of regular dependency from hackage.

Following scenario is not working.
packages.yaml:
```
library:
  source-dirs: src
  exposed-modules:
    - MyLib2
```

```
module ForHint where
import MyLib2
```

Error:
```
Could not find module MyLib2
```

but if extract MyLib2 into sub package the issue disappears!

stack.yaml:
```
packages:
- .
- subload
```

subload/packages.yaml:
```
library:
  source-dirs: src
  exposed-modules:
    - MyLib
```
